CREATE TABLE USUARIO1 (
NOMBRE VARCHAR(30) NOT NULL,
CONTRASEÑA VARCHAR(30) NOT NULL,
);
CREATE TABLE AULA2 (
NUMERO VARCHAR(30) NOT NULL,
LETRA VARCHAR(30) NOT NULL,
);
CREATE TABLE CURSO3 (
NOMBRE VARCHAR(30) NOT NULL,
AÑO  VARCHAR(30) NOT NULL,
);
CREATE TABLE EDIFICIO4 (
CALLE VARCHAR(30) NOT NULL,
NUMERO VARCHAR(30) NOT NULL,
);
